name: DiscordSRZ
version: 1.2.0
author: Cannicide
description: A lightweight, powerful alternative to DiscordSRV. Connects minecraft to a NodeJS discord bot.
main: us.cannicide.discordsrz.DiscordSRZ
commands:
  discord:
    description: The commands for DiscordSRZ.
    usage: /discord <help|link|unlink|reload>
permissions:
  discordsrz.admin:
    description: Admin permissions for DiscordSRZ.
    default: false
  discordsrz.use:
    description: Permission to use the /discord command.
    default: true